### ISSUE TITLE
Database password not match

### ISSUE THREAD

**Issue by MixMe** [yarcode/yii2-app-yarcode#20]
Command: docker-compose run --rm yii migrate
Error: Exception 'yii\db\Exception' with message 'SQLSTATE[08006] [7] FATAL:  password authentication failed for user "yiidock"'

**Comment by MixMe** [comment]
nothing changed:
cp .env.example .env

**Comment by MixMe** [comment]
In  yii2-app-yarcode/docker-compose.yml you have:

> environment:
>       POSTGRES_USER: "${DB_USERNAME}"
>       POSTGRES_PASSWORD: "${DB_USERNAME}"

maybe must be:

>       POSTGRES_USER: "${DB_USERNAME}"
>       POSTGRES_PASSWORD:  "${DB_PASSWORD}"

POSTGRES_PASSWORD =  "${DB_PASSWORD}" not  "${DB_USERNAME}"

**Comment by metalagman** [comment]
thank you for you help
fixed it here
https://github.com/yarcode/yii2-app-yarcode/releases/tag/1.7.2
